---
title: "Homer Theme"
subtitle: "Walkx"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by Walkx</p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

theme: dark
colors:
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "//GitHub"
    icon: "fas fa-github"
    items:
      - name: "Homer Theme"
        logo: "assets/tools/github.png"
        subtitle: "The official Homer Theme github!"
        tag: "github"
        tagstyle: "is-primary"
        url: "https://github.com/WalkxCode/Homer-Theme"
        target: "_blank"

  - name: "//Reddit"
    icon: "fas fa-reddit"
    items:
      - name: "The original reddit post!"
        logo: "assets/tools/reddit.png"
        subtitle: "Yes... this is Homer."
        tag: "reddit"
        tagstyle: "is-info"
        url: "https://www.reddit.com/r/selfhosted/comments/q9e82c/yes_this_is_homer_yes_i_spent_2_hours_customizing/"
        target: "_blank"
